resolver: lts-6.16

packages:
- '.'
- location:
    git: git@github.com:plow-technologies/cobalt-kiosk-form-template.git
    commit: fbacb0bcb6aeca765b9f58df650647c90f75bb35
  extra-dep: true
- location:
    git: git@github.com:plow-technologies/plow-extras.git
    commit: 1caf66300dccb79681f71be046a14ce566526964
  subdirs:
  - plow-extras-time
- location:
    git: git@github.com:plow-technologies/report-template.git
    commit: fa194badba274de144f3be95818197b4120fd3df
- location:
    git: git@github.com:plow-technologies/plow-mocks.git
    commit: 1dc4ee14268f7eddd1a7ae3c671d4effa425c4f4
  subdirs:
  - primitive-generator-mocks

extra-deps:
- quickbooks-0.5.0.1
- xlsx-0.2.0
- aeson-0.9.0.1
- aeson-serialize-0.0.0
- regex-genex-0.7.0
- serial-test-generators-0.1.3
- stream-monad-0.4.0.2
- logict-0.5.0.2

flags: {}

extra-package-dbs: []
